from __future__ import annotations

from datetime import datetime
from typing import Any, Generic, TypeVar, overload

_T = TypeVar("_T")

class OrmAttr(Generic[_T]):
    @overload
    def __get__(self, obj: None, owner: type[Any]) -> Any: ...
    @overload
    def __get__(self, obj: object, owner: type[Any]) -> _T: ...
    def __set__(self, obj: object, value: Any) -> None: ...

class _Model:
    def __init__(self, **kwargs: Any) -> None: ...

Base: Any
user_companies: Any

class Company(_Model):
    id: OrmAttr[int]
    name: OrmAttr[str]
    sector: OrmAttr[str]
    revenue_year: OrmAttr[float]
    created_at: OrmAttr[datetime]
    users: OrmAttr[list[User]]
    products: OrmAttr[list[Product]]

class User(_Model):
    id: OrmAttr[int]
    email: OrmAttr[str]
    full_name: OrmAttr[str]
    hashed_password: OrmAttr[str]
    role: OrmAttr[str]
    is_active: OrmAttr[bool]
    created_at: OrmAttr[datetime]
    companies: OrmAttr[list[Company]]

class Product(_Model):
    id: OrmAttr[int]
    company_id: OrmAttr[int]
    name: OrmAttr[str]
    category: OrmAttr[str]
    standard_cost: OrmAttr[float]
    sale_price: OrmAttr[float]
    stock_quantity: OrmAttr[int]
    min_stock: OrmAttr[int]
    created_at: OrmAttr[datetime]
    company: OrmAttr[Company]

class Customer(_Model):
    id: OrmAttr[int]
    company_id: OrmAttr[int]
    name: OrmAttr[str]
    segment: OrmAttr[str]
    email: OrmAttr[str]
    phone: OrmAttr[str]
    address: OrmAttr[str]
    document: OrmAttr[str]
    is_active: OrmAttr[bool]
    created_at: OrmAttr[datetime]

class Supplier(_Model):
    id: OrmAttr[int]
    company_id: OrmAttr[int]
    name: OrmAttr[str]
    cnpj: OrmAttr[str]
    contact_name: OrmAttr[str]
    email: OrmAttr[str]
    phone: OrmAttr[str]
    address: OrmAttr[str]
    payment_terms: OrmAttr[str]
    lead_time_days: OrmAttr[int]
    rating: OrmAttr[float]
    status: OrmAttr[str]
    created_at: OrmAttr[datetime]

class SupplierProduct(_Model):
    id: OrmAttr[int]
    supplier_id: OrmAttr[int]
    product_id: OrmAttr[int]
    supplier_sku: OrmAttr[str]
    unit_cost: OrmAttr[float]
    min_order_qty: OrmAttr[int]
    last_purchase_date: OrmAttr[datetime]
    created_at: OrmAttr[datetime]

class SalesOrder(_Model):
    id: OrmAttr[int]
    company_id: OrmAttr[int]
    customer_id: OrmAttr[int]
    product_id: OrmAttr[int]
    revenue: OrmAttr[float]
    discount: OrmAttr[float]
    total: OrmAttr[float]
    order_date: OrmAttr[datetime]
    created_at: OrmAttr[datetime]

class ProductionOrder(_Model):
    id: OrmAttr[int]
    company_id: OrmAttr[int]
    product_id: OrmAttr[int]
    planned_qty: OrmAttr[int]
    actual_qty: OrmAttr[int]
    planned_cost: OrmAttr[float]
    actual_cost: OrmAttr[float]
    planned_date: OrmAttr[datetime]
    actual_date: OrmAttr[datetime]
    status: OrmAttr[str]
    created_at: OrmAttr[datetime]

class Inventory(_Model):
    id: OrmAttr[int]
    company_id: OrmAttr[int]
    product_id: OrmAttr[int]
    warehouse_location: OrmAttr[str]
    quantity_on_hand: OrmAttr[int]
    quantity_reserved: OrmAttr[int]
    quantity_available: OrmAttr[int]
    unit_cost: OrmAttr[float]
    last_movement_date: OrmAttr[datetime]
    min_stock_level: OrmAttr[int]
    max_stock_level: OrmAttr[int]
    status: OrmAttr[str]
    created_at: OrmAttr[datetime]

class PurchaseOrder(_Model):
    id: OrmAttr[int]
    company_id: OrmAttr[int]
    supplier_id: OrmAttr[int]
    order_number: OrmAttr[str]
    status: OrmAttr[str]
    total_amount: OrmAttr[float]
    order_date: OrmAttr[datetime]
    expected_date: OrmAttr[datetime]
    received_date: OrmAttr[datetime]
    created_at: OrmAttr[datetime]

class PurchaseOrderItem(_Model):
    id: OrmAttr[int]
    purchase_order_id: OrmAttr[int]
    product_id: OrmAttr[int]
    quantity: OrmAttr[int]
    unit_cost: OrmAttr[float]
    total_cost: OrmAttr[float]
    received_qty: OrmAttr[int]

class FinancialStatement(_Model):
    id: OrmAttr[int]
    company_id: OrmAttr[int]
    statement_type: OrmAttr[str]
    period: OrmAttr[str]
    line_item: OrmAttr[str]
    value: OrmAttr[float]
    created_at: OrmAttr[datetime]

class FinancialUploadBatch(_Model):
    id: OrmAttr[int]
    company_id: OrmAttr[int]
    file_name: OrmAttr[str]
    periods: OrmAttr[str]
    rows_imported: OrmAttr[int]
    status: OrmAttr[str]
    created_at: OrmAttr[datetime]

class ErpFinancial(_Model):
    id: OrmAttr[int]
    company_id: OrmAttr[int]
    document_type: OrmAttr[str]
    document_number: OrmAttr[str]
    account_code: OrmAttr[str]
    account_name: OrmAttr[str]
    debit: OrmAttr[float]
    credit: OrmAttr[float]
    balance: OrmAttr[float]
    period: OrmAttr[str]
    posting_date: OrmAttr[datetime]
    created_at: OrmAttr[datetime]

class ERPImportBatch(_Model):
    id: OrmAttr[int]
    company_id: OrmAttr[int]
    data_type: OrmAttr[str]
    file_name: OrmAttr[str]
    rows_received: OrmAttr[int]
    rows_imported: OrmAttr[int]
    rows_rejected: OrmAttr[int]
    status: OrmAttr[str]
    error_message: OrmAttr[str]
    created_at: OrmAttr[datetime]

class ERPConnection(_Model):
    id: OrmAttr[int]
    company_id: OrmAttr[int]
    erp_type: OrmAttr[str]
    name: OrmAttr[str]
    connection_string: OrmAttr[str]
    host: OrmAttr[str]
    port: OrmAttr[int]
    database_name: OrmAttr[str]
    username: OrmAttr[str]
    password_encrypted: OrmAttr[str]
    api_key: OrmAttr[str]
    api_secret: OrmAttr[str]
    webhook_url: OrmAttr[str]
    auth_method: OrmAttr[str]
    extra_config: OrmAttr[str]
    is_active: OrmAttr[bool]
    status: OrmAttr[str]
    last_sync: OrmAttr[datetime]
    last_error: OrmAttr[str]
    sync_frequency_minutes: OrmAttr[int]
    enabled_modules: OrmAttr[str]
    created_at: OrmAttr[datetime]
    updated_at: OrmAttr[datetime]
    company: OrmAttr[Company]
    sync_logs: OrmAttr[list[ERPSyncLog]]
    field_mappings: OrmAttr[list[ERPFieldMapping]]

class ERPSyncLog(_Model):
    id: OrmAttr[int]
    connection_id: OrmAttr[int]
    sync_type: OrmAttr[str]
    entity_type: OrmAttr[str]
    records_found: OrmAttr[int]
    records_imported: OrmAttr[int]
    records_failed: OrmAttr[int]
    started_at: OrmAttr[datetime]
    completed_at: OrmAttr[datetime]
    finished_at: OrmAttr[datetime]
    duration_seconds: OrmAttr[float]
    status: OrmAttr[str]
    error_message: OrmAttr[str]
    details: OrmAttr[str]
    connection: OrmAttr[ERPConnection]

class ERPFieldMapping(_Model):
    id: OrmAttr[int]
    connection_id: OrmAttr[int]
    entity_type: OrmAttr[str]
    erp_field_name: OrmAttr[str]
    juno_field_name: OrmAttr[str]
    data_type: OrmAttr[str]
    transform_rule: OrmAttr[str]
    is_required: OrmAttr[bool]
    is_active: OrmAttr[bool]
    created_at: OrmAttr[datetime]
    connection: OrmAttr[ERPConnection]

class Role(_Model):
    id: OrmAttr[int]
    company_id: OrmAttr[int]
    name: OrmAttr[str]
    description: OrmAttr[str]
    is_system_role: OrmAttr[bool]
    permissions: OrmAttr[str]
    created_at: OrmAttr[datetime]

class UserRole(_Model):
    id: OrmAttr[int]
    user_id: OrmAttr[int]
    role_id: OrmAttr[int]
    granted_by: OrmAttr[int]
    granted_at: OrmAttr[datetime]
    expires_at: OrmAttr[datetime]
    role: OrmAttr[Role]

class AuditLog(_Model):
    id: OrmAttr[int]
    company_id: OrmAttr[int]
    user_id: OrmAttr[int]
    action: OrmAttr[str]
    resource_type: OrmAttr[str]
    resource_id: OrmAttr[int]
    old_values: OrmAttr[str]
    new_values: OrmAttr[str]
    ip_address: OrmAttr[str]
    user_agent: OrmAttr[str]
    session_id: OrmAttr[str]
    request_id: OrmAttr[str]
    success: OrmAttr[bool]
    error_message: OrmAttr[str]
    severity: OrmAttr[str]
    compliance_tags: OrmAttr[str]
    created_at: OrmAttr[datetime]
    source_table: OrmAttr[str]
    details: OrmAttr[str]
    user_name: OrmAttr[str]

class UserCompany(_Model):
    id: OrmAttr[int]
    user_id: OrmAttr[int]
    company_id: OrmAttr[int]
    role_in_tenant: OrmAttr[str]
    is_primary: OrmAttr[bool]
    joined_at: OrmAttr[datetime]

class ScoreHistory(_Model):
    id: OrmAttr[int]
    company_id: OrmAttr[int]
    score_date: OrmAttr[datetime]
    overall_score: OrmAttr[float]
    margin_score: OrmAttr[float]
    liquidity_score: OrmAttr[float]
    debt_score: OrmAttr[float]
    production_score: OrmAttr[float]
    data_quality_score: OrmAttr[float]
    details: OrmAttr[str]
    created_at: OrmAttr[datetime]

class ChatSession(_Model):
    id: OrmAttr[int]
    user_id: OrmAttr[int]
    company_id: OrmAttr[int]
    title: OrmAttr[str]
    created_at: OrmAttr[datetime]
    updated_at: OrmAttr[datetime]
    messages: OrmAttr[list[ChatMessage]]

class ChatMessage(_Model):
    id: OrmAttr[int]
    session_id: OrmAttr[int]
    role: OrmAttr[str]
    content: OrmAttr[str]
    tool_calls: OrmAttr[str]
    created_at: OrmAttr[datetime]
    session: OrmAttr[ChatSession]

class ReportDefinition(_Model):
    id: OrmAttr[int]
    company_id: OrmAttr[int]
    name: OrmAttr[str]
    description: OrmAttr[str]
    report_type: OrmAttr[str]
    data_source: OrmAttr[str]
    query_config: OrmAttr[str]
    filter_config: OrmAttr[str]
    column_config: OrmAttr[str]
    chart_config: OrmAttr[str]
    sort_config: OrmAttr[str]
    group_by_config: OrmAttr[str]
    is_template: OrmAttr[bool]
    template_category: OrmAttr[str]
    is_scheduled: OrmAttr[bool]
    schedule_cron: OrmAttr[str]
    schedule_recipients: OrmAttr[str]
    schedule_format: OrmAttr[str]
    created_by: OrmAttr[int]
    status: OrmAttr[str]
    created_at: OrmAttr[datetime]
    updated_at: OrmAttr[datetime]
    last_executed_at: OrmAttr[datetime]
    execution_count: OrmAttr[int]
    executions: OrmAttr[list[ReportExecution]]

class DashboardDefinition(_Model):
    id: OrmAttr[int]
    company_id: OrmAttr[int]
    name: OrmAttr[str]
    description: OrmAttr[str]
    layout_config: OrmAttr[str]
    widget_configs: OrmAttr[str]
    refresh_interval_seconds: OrmAttr[int]
    is_default: OrmAttr[bool]
    is_public: OrmAttr[bool]
    created_by: OrmAttr[int]
    status: OrmAttr[str]
    created_at: OrmAttr[datetime]
    updated_at: OrmAttr[datetime]

class ReportExecution(_Model):
    id: OrmAttr[int]
    report_id: OrmAttr[int]
    company_id: OrmAttr[int]
    executed_by: OrmAttr[int]
    status: OrmAttr[str]
    parameters: OrmAttr[str]
    row_count: OrmAttr[int]
    file_path: OrmAttr[str]
    file_format: OrmAttr[str]
    file_size_bytes: OrmAttr[int]
    execution_time_ms: OrmAttr[int]
    error_message: OrmAttr[str]
    started_at: OrmAttr[datetime]
    completed_at: OrmAttr[datetime]
    report: OrmAttr[ReportDefinition]

class ReportFavorite(_Model):
    id: OrmAttr[int]
    user_id: OrmAttr[int]
    report_id: OrmAttr[int]
    dashboard_id: OrmAttr[int]
    created_at: OrmAttr[datetime]

class MLModel(_Model):
    id: OrmAttr[int]
    company_id: OrmAttr[int]
    name: OrmAttr[str]
    model_type: OrmAttr[str]
    entity_type: OrmAttr[str]
    algorithm: OrmAttr[str]
    hyperparameters: OrmAttr[str]
    metrics: OrmAttr[str]
    model_path: OrmAttr[str]
    feature_columns: OrmAttr[str]
    target_column: OrmAttr[str]
    training_data_size: OrmAttr[int]
    last_trained_at: OrmAttr[datetime]
    status: OrmAttr[str]
    accuracy: OrmAttr[float]
    is_auto_ml: OrmAttr[bool]
    created_at: OrmAttr[datetime]
    updated_at: OrmAttr[datetime]
    predictions: OrmAttr[list[MLPrediction]]

class MLPrediction(_Model):
    id: OrmAttr[int]
    model_id: OrmAttr[int]
    company_id: OrmAttr[int]
    entity_id: OrmAttr[int]
    entity_type: OrmAttr[str]
    prediction_date: OrmAttr[datetime]
    predicted_value: OrmAttr[float]
    confidence_lower: OrmAttr[float]
    confidence_upper: OrmAttr[float]
    confidence_score: OrmAttr[float]
    actual_value: OrmAttr[float]
    error_rate: OrmAttr[float]
    features_used: OrmAttr[str]
    status: OrmAttr[str]
    created_at: OrmAttr[datetime]
    model: OrmAttr[MLModel]

class MLAnomaly(_Model):
    id: OrmAttr[int]
    company_id: OrmAttr[int]
    model_id: OrmAttr[int]
    entity_type: OrmAttr[str]
    entity_id: OrmAttr[int]
    anomaly_type: OrmAttr[str]
    severity: OrmAttr[str]
    detected_at: OrmAttr[datetime]
    metric_name: OrmAttr[str]
    metric_value: OrmAttr[float]
    expected_range_min: OrmAttr[float]
    expected_range_max: OrmAttr[float]
    description: OrmAttr[str]
    is_acknowledged: OrmAttr[bool]
    acknowledged_by: OrmAttr[int]
    acknowledged_at: OrmAttr[datetime]
    resolution_notes: OrmAttr[str]
    created_at: OrmAttr[datetime]

class MLRecommendation(_Model):
    id: OrmAttr[int]
    company_id: OrmAttr[int]
    model_id: OrmAttr[int]
    recommendation_type: OrmAttr[str]
    entity_type: OrmAttr[str]
    entity_id: OrmAttr[int]
    title: OrmAttr[str]
    description: OrmAttr[str]
    current_value: OrmAttr[float]
    recommended_value: OrmAttr[float]
    expected_impact: OrmAttr[float]
    confidence_score: OrmAttr[float]
    is_applied: OrmAttr[bool]
    applied_at: OrmAttr[datetime]
    applied_by: OrmAttr[int]
    result_value: OrmAttr[float]
    created_at: OrmAttr[datetime]

class ChatbotConversation(_Model):
    id: OrmAttr[int]
    company_id: OrmAttr[int]
    user_id: OrmAttr[int]
    session_id: OrmAttr[str]
    message: OrmAttr[str]
    response: OrmAttr[str]
    intent: OrmAttr[str]
    confidence: OrmAttr[float]
    context: OrmAttr[str]
    is_user_message: OrmAttr[bool]
    created_at: OrmAttr[datetime]

class DataSubjectRequest(_Model):
    id: OrmAttr[int]
    company_id: OrmAttr[int]
    request_type: OrmAttr[str]
    status: OrmAttr[str]
    data_subject_email: OrmAttr[str]
    data_subject_name: OrmAttr[str]
    data_subject_type: OrmAttr[str]
    request_details: OrmAttr[str]
    requested_at: OrmAttr[datetime]
    deadline_at: OrmAttr[datetime]
    completed_at: OrmAttr[datetime]
    completed_by: OrmAttr[int]
    response_data: OrmAttr[str]
    rejection_reason: OrmAttr[str]
    legal_basis: OrmAttr[str]
    created_at: OrmAttr[datetime]

class ConsentRecord(_Model):
    id: OrmAttr[int]
    company_id: OrmAttr[int]
    data_subject_email: OrmAttr[str]
    consent_type: OrmAttr[str]
    consent_given: OrmAttr[bool]
    consent_version: OrmAttr[str]
    ip_address: OrmAttr[str]
    user_agent: OrmAttr[str]
    consent_text: OrmAttr[str]
    withdrawn_at: OrmAttr[datetime]
    withdrawn_by: OrmAttr[int]
    created_at: OrmAttr[datetime]

class SecuritySettings(_Model):
    id: OrmAttr[int]
    company_id: OrmAttr[int]
    password_policy: OrmAttr[str]
    mfa_required: OrmAttr[bool]
    mfa_methods: OrmAttr[str]
    session_timeout_minutes: OrmAttr[int]
    max_login_attempts: OrmAttr[int]
    lockout_duration_minutes: OrmAttr[int]
    require_password_change_days: OrmAttr[int]
    allowed_ip_ranges: OrmAttr[str]
    data_retention_days: OrmAttr[int]
    audit_retention_days: OrmAttr[int]
    encryption_at_rest: OrmAttr[bool]
    encryption_in_transit: OrmAttr[bool]
    gdpr_enabled: OrmAttr[bool]
    lgpd_enabled: OrmAttr[bool]
    created_at: OrmAttr[datetime]
    updated_at: OrmAttr[datetime]

class EventLog(_Model):
    id: OrmAttr[int]
    company_id: OrmAttr[int]
    entity_type: OrmAttr[str]
    entity_id: OrmAttr[int]
    event_type: OrmAttr[str]
    old_state: OrmAttr[str]
    new_state: OrmAttr[str]
    user_id: OrmAttr[int]
    created_at: OrmAttr[datetime]

class LoginAttempt(_Model):
    id: OrmAttr[int]
    username: OrmAttr[str]
    ip_address: OrmAttr[str]
    success: OrmAttr[bool]
    failure_reason: OrmAttr[str]
    user_agent: OrmAttr[str]
    created_at: OrmAttr[datetime]

class UserMarking(_Model):
    id: OrmAttr[int]
    user_id: OrmAttr[int]
    marking: OrmAttr[str]
    granted_by: OrmAttr[int]
    granted_at: OrmAttr[datetime]
    valid_until: OrmAttr[datetime]
    reason: OrmAttr[str]
    revoked: OrmAttr[bool]
    revoked_at: OrmAttr[datetime]
    revoked_by: OrmAttr[int]

class DatasetSnapshot(_Model):
    id: OrmAttr[int]
    name: OrmAttr[str]
    description: OrmAttr[str]
    object_type: OrmAttr[str]
    company_id: OrmAttr[int]
    created_by: OrmAttr[int]
    created_at: OrmAttr[datetime]
    row_count: OrmAttr[int]
    payload: OrmAttr[str]

class SnapshotIndex(_Model):
    id: OrmAttr[int]
    snapshot_id: OrmAttr[int]
    object_id: OrmAttr[int]

ErpImportBatch = ERPImportBatch
